# Generated by Django 5.0.6 on 2024-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subastas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('ofertaInicial', models.IntegerField(max_length=10)),
                ('imagen', models.CharField(max_length=64)),
            ],
        ),
    ]
