# Generated by Django 5.0.6 on 2024-09-10 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_subastas_imagen_alter_subastas_ofertainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subastas',
            name='imagen',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofertaActual', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo', to='auctions.subastas')),
                ('ofertanteActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
