# Generated by Django 5.0.6 on 2024-10-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_seguimientosubasta_user_listaseguimiento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguimientosubasta',
            unique_together={('user', 'subasta')},
        ),
    ]
