# Generated by Django 5.0.6 on 2024-11-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='subastas',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
