# Generated by Django 5.1.2 on 2024-12-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_subastas_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subastas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='subastas/'),
        ),
    ]
