# Generated by Django 5.0.6 on 2024-12-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_subastas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='subastas',
            name='ofertaActual',
            field=models.IntegerField(default=0),
        ),
    ]
