# Generated by Django 5.0.6 on 2024-12-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_subastas_ofertaactual'),
    ]

    operations = [
        migrations.AddField(
            model_name='subastas',
            name='Categoria',
            field=models.CharField(default='Futbolistas', max_length=50),
        ),
    ]
