# Generated by Django 5.0.6 on 2024-12-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_subastas_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subastas',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
