# Generated by Django 5.0.6 on 2024-12-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_categoria_subastas_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subastas',
            name='categoria',
            field=models.CharField(choices=[('futbolistas', 'Futbolistas'), ('articulosLimpieza', 'Artículos de Limpieza')], default='futbolistas', max_length=50),
        ),
    ]
